
// This file is part of the MDCII Game Engine.
// Copyright (C) 2015  Benedikt Freisen
// 
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

#include "grafikinfo.hpp"

#include <stddef.h>

g_t *grafikinfo[] =
{
NULL,
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 

/* 101 */  &gras0_gruen,
/* 102 */  &gras1_gruen,
/* 103 */  &gras2_gruen,
/* 104 */  &gras3_gruen,
/* 105 */  &gras4_gruen,
/* 106 */  &gras5_gruen,
  
NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 

/* 141 */  &wueste0,
/* 142 */  &wueste1,
/* 143 */  &wueste2,
/* 144 */  &wueste3,
/* 145 */  &wueste4,
/* 146 */  &wueste5,
/* 147 */  &wueste6,
/* 148 */  &wueste7,
/* 149 */  &wueste8,
/* 150 */  &wueste9,
  
/* 151 */  &gras0_braun,
/* 152 */  &gras1_braun,
/* 153 */  &gras2_braun,
/* 154 */  &gras3_braun,
/* 155 */  &gras4_braun,
/* 156 */  &gras5_braun,
/* 157 */  &gras6_braun,
/* 158 */  &gras7_braun,
/* 159 */  &gras8_braun,
/* 160 */  &gras9_braun,

/* 161 */  &gras0,
/* 162 */  &gras1,
/* 163 */  &gras2,
/* 164 */  &gras3,
/* 165 */  &gras4,
/* 166 */  &gras5,
/* 167 */  &gras6,
/* 168 */  &gras7,
/* 169 */  &gras8,
/* 170 */  &gras9,
  
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,

/* 181 */  &pflanzen0,
/* 182 */  &pflanzen1,
/* 183 */  &pflanzen2,
/* 184 */  &pflanzen3,
/* 185 */  &pflanzen4,
/* 186 */  &pflanzen5,
/* 187 */  &pflanzen6,
/* 188 */  &pflanzen7,
/* 189 */  &pflanzen8,
/* 190 */  &pflanzen9,
   
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, 
  
/* 303 */  &stadttor,
/* 304 */  &tor_stein,
/* 305 */  &wachturm_stein_land,
/* 306 */  &wachturm_stein_kueste,

NULL, NULL, NULL, NULL, 

/* 311 */  &burg,
NULL, 
/* 313 */  &burg_gross,
NULL, 
/* 315 */  &festung,
  
NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
  
/* 401 */  &strasse_gerade,
/* 402 */  &strasse_ecke,
/* 403 */  &strasse_t,
/* 404 */  &strasse_kreuzung,
  
NULL, NULL, NULL, NULL, NULL, NULL, 

/* 411 */  &weg_gerade,
/* 412 */  &weg_ecke,
/* 413 */  &weg_t,
/* 414 */  &weg_kreuzung,

NULL, NULL, NULL, NULL, NULL, NULL, 

/* 421 */  &platz1,
/* 422 */  &platz2,
/* 423 */  &platz3,
/* 424 */  &zierbaum,
  
NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 

/* 501 */  &windmuehle,
NULL, 
/* 503 */  &baeckerei,
NULL,   
/* 505 */  &schneiderei,
NULL, 
/* 507 */  &webstube,
NULL, 
/* 509 */  &wassermuehle,
NULL, 
/* 511 */  &metzger,
NULL, 
/* 513 */  &steinmetz,
NULL, 
/* 515 */  &werkzeugschmiede,
NULL, 
/* 517 */  &schwertschmiede,
NULL, 
/* 519 */  &rumbrennerei,
NULL, 
/* 521 */  &erzschmelze,
  
NULL, NULL, NULL, 

/* 525 */  &tabakwarenladen,
NULL, 
/* 527 */  &kanonengiesserei,
NULL, 
/* 529 */  &musketenbauer,
NULL, 
/* 531 */  &weberei,
NULL, 
/* 533 */  &goldschmiede,
  
NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, 

/* 605 */  &pionier1,
/* 606 */  &pionier2,
/* 607 */  &pionier3,
/* 608 */  &pionier4,
/* 609 */  &pionier5,
/* 610 */  &pionier6,
/* 611 */  &pionier7,

NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 

/* 621 */  &siedler1,
/* 622 */  &siedler2,
/* 623 */  &siedler3,
/* 624 */  &siedler4,
/* 625 */  &siedler5,
  
NULL, NULL, NULL, NULL, NULL, 

/* 631 */  &buerger1,
/* 632 */  &buerger2,
/* 633 */  &buerger3,
/* 634 */  &buerger4,
/* 635 */  &buerger5,
/* 636 */  &buerger6,
  
NULL, NULL, NULL, NULL, 

/* 641 */  &kaufleute1,
/* 642 */  &kaufleute2,
/* 643 */  &kaufleute3,
/* 644 */  &kaufleute4,
/* 645 */  &kaufleute5,
  
NULL, NULL, NULL, NULL, NULL, 

/* 651 */  &aristokraten1,
/* 652 */  &aristokraten2,
/* 653 */  &aristokraten3,
/* 654 */  &aristokraten4,
/* 655 */  &aristokraten5,
/* 656 */  &aristokraten6,
  
NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 

/* 801 */  &kathedrale,
NULL, 
/* 803 */  &kapelle,
NULL, 
/* 805 */  &kirche,
NULL, 
/* 807 */  &wirtshaus,
NULL, 
/* 809 */  &marktplatz,
NULL, 
/* 811 */  &feuerwehr,
NULL, 
/* 813 */  &badehaus,
NULL, 
/* 815 */  &theater,
NULL, 
/* 817 */  &arzt,
NULL, 
/* 819 */  &hochschule,
NULL, 
/* 821 */  &schule,

NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 

/* 831 */  &schloss,

NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 

/* 841 */  &galgen,

NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 

/* 851 */  &denkmal,
  
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 

/* 901 */  &fluss0_gerade,
/* 902 */  &fluss1_gerade,
/* 903 */  &fluss0_gabelung,
/* 904 */  &fluss0_biegung,
/* 905 */  &fluss1_biegung,
  
NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
  
/* 1011 */  &kueste0_1_2,
/* 1012 */  &kueste1_1_2,
/* 1013 */  &kueste2_1_2,
/* 1014 */  &kueste3_1_2,
/* 1015 */  &kueste4_1_2,
/* 1016 */  &kueste5_1_2,
/* 1017 */  &kueste6_1_2,
/* 1018 */  &kueste7_1_2,
/* 1019 */  &kueste8_1_2,
/* 1020 */  &kueste9_1_2,
  
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 

/* 1031 */  &kueste0_3_4,
/* 1032 */  &kueste1_3_4,
/* 1033 */  &kueste2_3_4,
/* 1034 */  &kueste3_3_4,
  
NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 

/* 1051 */  &kueste0_1_4,
/* 1052 */  &kueste1_1_4,
/* 1053 */  &kueste2_1_4,
  
NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 

/* 1071 */  &kueste_muendung,
NULL, 
/* 1073 */  &anlegestelle,
NULL, 
/* 1075 */  &fischer,
  
NULL, NULL, NULL, NULL, NULL, 

/* 1081 */  &kueste0_felsig,
/* 1082 */  &kueste1_felsig,
/* 1083 */  &kueste2_felsig,
/* 1084 */  &kueste3_felsig,
  
NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, 

/* 1103 */  &berg2,
/* 1104 */  &berg5,
/* 1105 */  &berg6,
/* 1106 */  &berg3,
/* 1107 */  &berg4,
/* 1108 */  &vulkan,
/* 1109 */  &berg0,
/* 1110 */  &berg1,
  
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 

/* 1201 */  &meer,
/* 1202 */  &meer_flach_fischgruende,
/* 1203 */  &meer_flach,
/* 1204 */  &fischgruende,
/* 1205 */  &strand0_1_2,
/* 1206 */  &strand0_3_4,
/* 1207 */  &strand0_1_4,
/* 1208 */  &strand0_muendung,
/* 1209 */  &fischgruende_meer,
  
NULL, 
NULL, NULL, NULL, 

/* 1214 */  &strand1_1_2,
/* 1215 */  &strand2_1_2,
/* 1216 */  &strand3_1_2,
/* 1217 */  &strand4_1_2,
/* 1218 */  &strand5_1_2,
  
NULL, NULL, 

/* 1221 */  &strand1_3_4,
  
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 

/* 1231 */  &dreck0,
/* 1232 */  &dreck1,
/* 1233 */  &wrack,
/* 1234 */  &skelett,
/* 1235 */  &felsbogen0,
/* 1236 */  &felsbogen1,
/* 1237 */  &felsformation,
  
NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 

/* 1251 */  &meer, /* befischt */
/* 1252 */  &meer_flach_fischgruende,
  
NULL, 

/* 1254 */  &fischgruende, /* befischt */

NULL, NULL, NULL, NULL, 

/* 1259 */  &fischgruende, /* befischt */

NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 

/* 1301 */  &weizenfeld,
/* 1302 */  &weizenfeld_fertig,
  
/* 1303 */  &baum0_nord,
/* 1304 */  &baum0_nord_fertig,
/* 1305 */  &baum1_nord,
/* 1306 */  &baum1_nord_fertig,
/* 1307 */  &baum2_nord,
/* 1308 */  &baum2_nord_fertig,
/* 1309 */  &baum3_nord,
/* 1310 */  &baum3_nord_fertig,
/* 1311 */  &baum4_nord,
/* 1312 */  &baum4_nord_fertig,
/* 1313 */  &baum5_nord,
/* 1314 */  &baum5_nord_fertig,
/* 1315 */  &baum6_nord,
/* 1316 */  &baum6_nord_fertig,
/* 1317 */  &baum7_nord,
/* 1318 */  &baum7_nord_fertig,
/* 1319 */  &baum8_nord,
/* 1320 */  &baum8_nord_fertig,
/* 1321 */  &baum9_nord,
/* 1322 */  &baum9_nord_fertig,
/* 1323 */  &baum10_nord,
/* 1324 */  &baum10_nord_fertig,
  
NULL, NULL, NULL, NULL, NULL, NULL, 

/* 1331 */  &baumwollfeld,
/* 1332 */  &baumwollfeld_fertig,
  
NULL, NULL, 

/* 1335 */  &tabakfeld,
/* 1336 */  &tabakfeld_fertig,
/* 1337 */  &kakaofeld,
/* 1338 */  &kakaofeld_fertig,
/* 1339 */  &zuckerrohrfeld,
/* 1340 */  &zuckerrohrfeld_fertig,
/* 1341 */  &gewuerzfeld,
/* 1342 */  &gewuerzfeld_fertig,
/* 1343 */  &weinfeld,
/* 1344 */  &weinfeld_fertig,
  
NULL, NULL, NULL, NULL, NULL, NULL, 

/* 1351 */  &baum0_sued,
/* 1352 */  &baum0_sued_fertig,
/* 1353 */  &baum1_sued,
/* 1354 */  &baum1_sued_fertig,
/* 1355 */  &baum2_sued,
/* 1356 */  &baum2_sued_fertig,
/* 1357 */  &baum3_sued,
/* 1358 */  &baum3_sued_fertig,
/* 1359 */  &baum4_sued,
/* 1360 */  &baum4_sued_fertig,
/* 1361 */  &baum5_sued,
/* 1362 */  &baum5_sued_fertig,
/* 1363 */  &baum6_sued,
/* 1364 */  &baum6_sued_fertig,
/* 1365 */  &baum7_sued,
/* 1366 */  &baum7_sued_fertig,
/* 1367 */  &baum8_sued,
/* 1368 */  &baum8_sued_fertig,
/* 1369 */  &baum9_sued,
/* 1370 */  &baum9_sued_fertig,
/* 1371 */  &baum10_sued,
/* 1372 */  &baum10_sued_fertig,
  
NULL, NULL, 

/* 1375 */  &tabakfeld_trocken,
NULL, 
/* 1377 */  &kakaofeld_trocken,
NULL, 
/* 1379 */  &zuckerrohrfeld_trocken,
NULL, 
/* 1381 */  &gewuerzfeld_trocken,
NULL, 
/* 1383 */  &weinfeld_trocken,
  
NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, 

/* 1405 */  &wachturm_holz_land,
/* 1406 */  &wachturm_holz_kueste,
  
NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
  
/* 1501 */  &gewuerzplantage,
NULL, 
/* 1503 */  &bauernhof,
NULL, 
/* 1505 */  &baumwollplantage,
NULL, 
/* 1507 */  &tabakplantage,
NULL, 
/* 1509 */  &kakaoplantage,
NULL, 
/* 1511 */  &zuckerrohrplantage,
NULL, 
/* 1513 */  &rinderfarm,
NULL, 
/* 1515 */  &schaffarm,
NULL, 
/* 1517 */  &weingut,

NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 

/* 1601 */  &holzbruecke,
NULL, 
/* 1603 */  &steinbruecke,

NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
  
/* 2001 */  &holzfaeller,
NULL, 
/* 2003 */  &jagdhuette,
  
NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
  
/* 2101 */  &kontor1,
NULL, 
/* 2103 */  &kontor2,
NULL, 
/* 2105 */  &kontor3,
NULL, 
/* 2107 */  &kontor4,

NULL, NULL, NULL, 

/* 2111 */  &werft_gross,

NULL, NULL, NULL, 

/* 2115 */  &werft,

NULL, NULL, NULL, NULL, NULL, 

/* 2121 */  &kontor1_kaputt,
NULL, 
/* 2123 */  &kontor2_kaputt,
NULL, 
/* 2125 */  &kontor3_kaputt,
NULL, 
/* 2127 */  &kontor4_kaputt,

NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 


/* 2201 */  &haeuptlingshuette_stein,
/* 2202 */  &kriegerhuette_stein,
/* 2203 */  &eingeborenenhuette_stein,
/* 2204 */  &gewuerzlager_stein,
/* 2205 */  &tabaklager_stein,

NULL, NULL, NULL, NULL, NULL, 

/* 2211 */  &pyramide,

NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 

/* 2221 */  &piratenkontor,
/* 2222 */  &piratenhaus1,
/* 2223 */  &piratenhaus2,
/* 2224 */  &piratenwirtshaus,

NULL, NULL, NULL, NULL, NULL, NULL, 

/* 2231 */  &haeuptlingshuette,
/* 2232 */  &eingeborenenhuette,
/* 2233 */  &kriegerhuette,
/* 2234 */  &gewuerzlager,
/* 2235 */  &tabaklager,

NULL, NULL, NULL, NULL, NULL, 

/* 2241 */  &piratenturm_land,
/* 2242 */  &piratenturm_kueste,
  
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 

/* 2301 */  &hang0,
/* 2302 */  &hang1,
/* 2303 */  &hang2,
/* 2304 */  &hang3,
/* 2305 */  &hang4,
/* 2306 */  &hang5,
/* 2307 */  &hang6,
/* 2308 */  &hang7,
/* 2309 */  &hang8,
/* 2310 */  &hang9,
/* 2311 */  &quelle,

NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 

/* 2321 */  &hang0_1_4,
/* 2322 */  &hang1_1_4,

NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 

/* 2341 */  &hang0_3_4,
/* 2342 */  &hang1_3_4,
  
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 

/* 2401 */  &erzmine,
NULL, 
/* 2403 */  &erzmine_tief,
NULL, 
/* 2405 */  &goldmine,
NULL, 
/* 2407 */  &steinbruch,

NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 

/* 2501 */  &steinwall_gerade_land,
/* 2502 */  &steinwall_ecke_land,
/* 2503 */  &steinwall_turm_land,
  
NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 

/* 2521 */  &palisade_gerade_land,
/* 2522 */  &palisade_ecke_land,
/* 2523 */  &palisade_turm_land,
  
NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 

/* 2541 */  &steinwall_gerade_kueste,
/* 2542 */  &steinwall_ecke_kueste,
/* 2543 */  &steinwall_turm_kueste,
  
NULL, NULL, NULL, NULL, NULL, NULL, NULL, 

/* 2551 */  &steinwall_gerade_fluss,
/* 2552 */  &steinwall_ecke_fluss,
/* 2553 */  &steinwall_turm_fluss,
  
NULL, NULL, NULL, NULL, NULL, NULL, NULL, 

/* 2561 */  &palisade_gerade_kueste,
/* 2562 */  &palisade_ecke_kueste,
/* 2563 */  &palisade_turm_kueste,
  
NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 

/* 2601 */  &truemmer0,
/* 2602 */  &truemmer1,
/* 2603 */  &truemmer2,
/* 2604 */  &truemmer3,
/* 2605 */  &truemmer4,
/* 2606 */  &truemmer5,
  
NULL, NULL, NULL, 

/* 2610 */  &truemmer1_kueste,
/* 2611 */  &truemmer6,
/* 2612 */  &truemmer7,
/* 2613 */  &truemmer8,
/* 2614 */  &truemmer9,
/* 2615 */  &truemmer10,
/* 2616 */  &truemmer11,
  
NULL, NULL, NULL, 

/* 2620 */  &truemmer0_kueste,
/* 2621 */  &verbranntes_feld0,
/* 2622 */  &verbranntes_feld1,
  
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 

/* 2631 */  &wegreste0, /* zu überprüfen */
/* 2632 */  &wegreste1,
/* 2633 */  &wegreste2,
/* 2634 */  &wegreste3,
/* 2635 */  &wegreste4,
/* 2636 */  &wegreste3,
/* 2637 */  &wegreste4,
/* 2638 */  &wegreste5,
  
NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 

/* 2701 */  &gras0,
/* 2702 */  &gras0,
/* 2703 */  &gras0,
/* 2704 */  &gras0,
/* 2705 */  &gras7,
/* 2706 */  &gras7,
/* 2707 */  &sand0,
/* 2708 */  &sand0,
/* 2709 */  &gras0,
/* 2710 */  &gras0,
/* 2711 */  &gras0,
/* 2712 */  &gras0,
/* 2713 */  &gras0,
/* 2714 */  &gras0,
/* 2715 */  &gras0,
/* 2716 */  &gras0,
/* 2717 */  &gras0,
/* 2718 */  &gras0,
/* 2719 */  &gras0,
/* 2720 */  &gras0,
  
/* 2721 */  &gras0b,
/* 2722 */  &gras0b,
/* 2723 */  &gras1b,
/* 2724 */  &gras1b,
/* 2725 */  &gras2b,
/* 2726 */  &gras2b,
/* 2727 */  &gras3b,
/* 2728 */  &gras3b,
/* 2729 */  &gras4b,
/* 2730 */  &gras4b,
/* 2731 */  &gras5b,
/* 2732 */  &gras5b,
/* 2733 */  &gras6b,
/* 2734 */  &gras6b,
/* 2735 */  &gras7b,
/* 2736 */  &gras7b,
/* 2737 */  &gras8b,
/* 2738 */  &gras8b,
/* 2739 */  &gras9b,
/* 2740 */  &gras9b,
/* 2741 */  &pflanzen0b,
/* 2742 */  &pflanzen0b,
/* 2743 */  &pflanzen1b,
/* 2744 */  &pflanzen1b,
/* 2745 */  &pflanzen2b,
/* 2746 */  &pflanzen2b,
/* 2747 */  &pflanzen3b,
/* 2748 */  &pflanzen3b,
/* 2749 */  &pflanzen4b,
/* 2750 */  &pflanzen4b,
/* 2751 */  &pflanzen5b,
/* 2752 */  &pflanzen5b,
/* 2753 */  &pflanzen6b,
/* 2754 */  &pflanzen6b,
/* 2755 */  &pflanzen7b,
/* 2756 */  &pflanzen7b,
/* 2757 */  &pflanzen8b,
/* 2758 */  &pflanzen8b,
/* 2759 */  &pflanzen9b,
/* 2760 */  &pflanzen9b,
  
/* 2761 */  &wueste0,
/* 2762 */  &wueste0,
/* 2763 */  &wueste1,
/* 2764 */  &wueste1,
/* 2765 */  &wueste2,
/* 2766 */  &wueste2,
/* 2767 */  &wueste3,
/* 2768 */  &wueste3,
/* 2769 */  &wueste4,
/* 2770 */  &wueste4,
/* 2771 */  &wueste5,
/* 2772 */  &wueste5,
/* 2773 */  &wueste6,
/* 2774 */  &wueste6,
/* 2775 */  &wueste7,
/* 2776 */  &wueste7,
/* 2777 */  &wueste8,
/* 2778 */  &wueste8,
/* 2779 */  &wueste9,
/* 2780 */  &wueste9,
  
/* 2781 */  &gras0_braun,
/* 2782 */  &gras0_braun,
/* 2783 */  &gras1_braun,
/* 2784 */  &gras1_braun,
/* 2785 */  &gras2_braun,
/* 2786 */  &gras2_braun,
/* 2787 */  &gras3_braun,
/* 2788 */  &gras3_braun,
/* 2789 */  &gras4_braun,
/* 2790 */  &gras4_braun,
/* 2791 */  &gras5_braun,
/* 2792 */  &gras5_braun,
/* 2793 */  &gras6_braun,
/* 2794 */  &gras6_braun,
/* 2795 */  &gras7_braun,
/* 2796 */  &gras7_braun,
/* 2797 */  &gras8_braun,
/* 2798 */  &gras8_braun,
/* 2799 */  &gras9_braun,
/* 2800 */  &gras9_braun,
  
/* 2801 */  &baum0_sued,
/* 2802 */  &baum0_sued_fertig,
/* 2803 */  &baum1_sued,
/* 2804 */  &baum1_sued_fertig,
/* 2805 */  &baum2_sued,
/* 2806 */  &baum2_sued_fertig,
/* 2807 */  &baum3_sued,
/* 2808 */  &baum3_sued_fertig,
/* 2809 */  &baum4_sued,
/* 2810 */  &baum4_sued_fertig,
/* 2811 */  &baum5_sued,
/* 2812 */  &baum5_sued_fertig,
/* 2813 */  &baum6_sued,
/* 2814 */  &baum6_sued_fertig,
/* 2815 */  &baum7_sued,
/* 2816 */  &baum7_sued_fertig,
/* 2817 */  &baum8_sued,
/* 2818 */  &baum8_sued_fertig,
/* 2819 */  &baum9_sued,
/* 2820 */  &baum9_sued_fertig,
/* 2821 */  &baum10_sued,
/* 2822 */  &baum10_sued_fertig,
};
